@extends('layout.app')
@section('title', 'Assignments')
@push('styles')<link rel="stylesheet" href="{{ asset('css/assignments.css') }}">@endpush
@section('content')
@php
    $assignments = [
        ['Poster Installation','City Clean Drive','Ramesh Kumar','Installation','Single','28 Sep 2026','In Progress'],['Market Survey','Market Survey','Priya Sharma','Survey','Single','27 Sep 2026','Completed'],['Road Cleaning','River Awareness','Amit Singh','Cleaning','Start-End','26 Sep 2026','Pending'],['Shop Visit','Green City Initiative','Neha Verma','Visit','Single','25 Sep 2026','In Progress'],['Awareness Drive','Poster Campaign','Suresh Patel','Campaign','Continuous','24 Sep 2026','Completed'],['River Cleanup','River Awareness','Vikram Singh','Cleaning','Start-End','23 Sep 2026','In Progress'],['Banner Installation','City Clean Drive','Anil Yadav','Installation','Single','22 Sep 2026','Pending'],['Community Survey','Market Survey','Kavita Joshi','Survey','Single','21 Sep 2026','On Hold'],['Plantation Drive','Green City Initiative','Manish Gupta','Campaign','Continuous','20 Sep 2026','In Progress'],['Waste Collection','City Clean Drive','Pooja Mehta','Cleaning','Start-End','19 Sep 2026','Completed'],
    ];
@endphp
<nav class="breadcrumbs"><a href="{{ route('web.dashboard') }}"><svg class="icon"><use href="#home"/></svg>Dashboard</a><span>&rsaquo;</span><span>Assignments</span></nav>
<div class="page-heading assignments-heading"><div><h1>Assignments</h1><p>Create, manage and track field assignments for workers.</p></div><a class="primary-button" href="{{ route('web.assignments.create') }}"><span>+</span>Create New Assignment</a></div>
<div class="assignment-stats"><article class="assignment-stat blue"><span><svg class="icon"><use href="#clipboard"/></svg></span><div><h2>Total Assignments</h2><strong>56</strong><p>+ 12 this month</p></div></article><article class="assignment-stat green"><span>✓</span><div><h2>Active Assignments</h2><strong>32</strong><p>+ 8 this month</p></div></article><article class="assignment-stat orange"><span>◷</span><div><h2>On Hold</h2><strong>8</strong><p>+ 2 this month</p></div></article><article class="assignment-stat purple"><span>✓</span><div><h2>Completed</h2><strong>16</strong><p>+ 4 this month</p></div></article></div>
<div class="assignment-layout"><section class="assignment-table-card"><div class="assignment-filters"><label class="assignment-search"><svg class="icon"><use href="#search"/></svg><input placeholder="Search assignments by title, project, worker..."></label><select><option>All Companies</option></select><select><option>All Projects</option></select><select><option>All Activity Types</option></select><select><option>All Status</option></select><button type="button">Reset</button></div><div class="company-table-scroll"><table class="assignment-table"><thead><tr><th>□</th><th>#</th><th>Assignment Title</th><th>Project</th><th>Worker</th><th>Activity Type</th><th>Mode</th><th>Due Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach($assignments as $assignment)<tr><td>□</td><td>{{ $loop->iteration }}</td><td><strong>{{ $assignment[0] }}</strong><small>ASG{{ str_pad((string) $loop->iteration, 3, '0', STR_PAD_LEFT) }}</small></td><td>{{ $assignment[1] }}</td><td><strong>{{ $assignment[2] }}</strong><small>USR{{ str_pad((string) $loop->iteration, 3, '0', STR_PAD_LEFT) }}</small></td><td><span class="activity-badge">{{ $assignment[3] }}</span></td><td><span class="mode-badge">{{ $assignment[4] }}</span></td><td>{{ $assignment[5] }}</td><td><span class="assignment-status {{ strtolower(str_replace(' ', '-', $assignment[6])) }}">{{ $assignment[6] }}</span></td><td><button class="assignment-action">View</button><button class="assignment-action">Edit</button><button class="assignment-action delete">Delete</button></td></tr>@endforeach</tbody></table></div><div class="company-footer"><label class="page-size">Show <select><option>10</option></select> entries</label><nav class="pagination"><button>1</button><button>2</button><button>3</button></nav></div></section>
<aside id="assignment-form" class="assignment-form-card"><div class="form-heading"><h2>Create New Assignment</h2><button id="close-assignment-form" type="button">×</button></div><form id="new-assignment-form"><label>Company <em>*</em><select required><option>ABC Company</option><option>XYZ Pvt Ltd</option></select></label><label>Project <em>*</em><select required><option>City Clean Drive</option><option>Market Survey</option></select></label><label>Assignment Title <em>*</em><input required placeholder="Enter assignment title"></label><label>Activity Type <em>*</em><select required><option value="" selected disabled>Select activity type</option><option>Installation</option><option>Survey</option><option>Cleaning</option></select></label><label>Activity Mode <em>*</em><input value="Single Submission (Photo + Location)" readonly></label><label>Assign to Worker <em>*</em><select required><option value="" selected disabled>Select worker</option><option>Ramesh Kumar</option><option>Priya Sharma</option></select></label><label>Due Date <em>*</em><input required type="date"></label><label>Description<textarea id="assignment-description" maxlength="500" placeholder="Enter assignment description..."></textarea><small id="assignment-description-count">0/500</small></label><div class="assignment-actions"><button class="secondary-button" id="cancel-assignment" type="button">Cancel</button><button class="primary-button" type="submit">Create Assignment</button></div></form></aside></div><div id="assignment-toast" class="company-toast" hidden></div>
@endsection
@push('scripts')<script src="{{ asset('js/assignments.js') }}"></script>@endpush
