@extends('layout.app')
@section('title', 'Activity Sessions')
@push('styles')<link rel="stylesheet" href="{{ asset('css/session-list.css') }}">@endpush
@section('content')
@php($sessions = [['SES0001','Ramesh Kumar','Canopy Installation','City Clean Drive','28 Sep 2026 09:15 AM','3h 25m','Active','active'],['SES0002','Priya Sharma','Shop Visit','Market Survey','28 Sep 2026 09:40 AM','2h 30m','Pending Review','pending'],['SES0003','Amit Singh','Road Cleaning','River Awareness','28 Sep 2026 08:20 AM','4h 15m','Completed','completed'],['SES0004','Neha Verma','Canopy Installation','Green City Initiative','27 Sep 2026 10:05 AM','5h 10m','Completed','completed'],['SES0005','Suresh Patel','Field Setup','Awareness Drive','27 Sep 2026 09:30 AM','1h 20m','Rejected','rejected'],['SES0006','Vikram Yadav','Market Survey','City Clean Drive','27 Sep 2026 11:00 AM','2h 10m','Completed','completed']])
<nav class="breadcrumbs"><a href="{{ route('web.dashboard') }}"><svg class="icon"><use href="#home"/></svg>Dashboard</a><span>&rsaquo;</span><span>Activity Sessions</span></nav>
<div class="page-heading session-heading"><div><h1>Activity Sessions</h1><p>Monitor start-end field activities, working duration and review status.</p></div><div class="session-links"><a href="{{ route('web.activity-sessions.live') }}">Live Worker Tracking</a><a href="{{ route('web.activity-sessions.map') }}">View Full Map</a></div></div>
<div class="session-stats"><article class="session-stat blue"><span><svg class="icon"><use href="#clock"/></svg></span><div><h2>Total Sessions</h2><strong>24</strong><p>↑ 20%</p></div></article><article class="session-stat green"><span>▶</span><div><h2>Active Now</h2><strong>6</strong><p>↑ 50%</p></div></article><article class="session-stat orange"><span><svg class="icon"><use href="#clock"/></svg></span><div><h2>Pending Review</h2><strong>5</strong><p>↑ 25%</p></div></article><article class="session-stat purple"><span>✓</span><div><h2>Completed</h2><strong>11</strong><p>↑ 10%</p></div></article><article class="session-stat blue"><span>×</span><div><h2>Rejected</h2><strong>2</strong><p>↓ 0%</p></div></article></div>
<div class="session-layout"><section class="sessions-main"><div class="session-filters"><input placeholder="Search by worker, assignment or session ID..."><select><option>All Companies</option></select><select><option>All Projects</option></select><select><option>All Status</option></select><input type="date"><button>Reset</button></div><h2 style="padding:0 14px;font-size:14px">Activity Sessions (24)</h2><table class="session-table"><tr><th>#</th><th>Session ID</th><th>Worker</th><th>Assignment</th><th>Project</th><th>Start Time</th><th>Duration</th><th>End Time</th><th>Status</th><th>Actions</th></tr>@foreach($sessions as $session)<tr><td>{{ $loop->iteration }}</td><td>{{ $session[0] }}</td><td><b>{{ $session[1] }}</b><small>USR00{{ $loop->iteration }}</small></td><td>{{ $session[2] }}</td><td>{{ $session[3] }}</td><td>{{ $session[4] }}</td><td>{{ $session[5] }}</td><td>-</td><td><span class="session-status {{ $session[7] }}">{{ $session[6] }}</span></td><td><button class="session-view" type="button">◉</button></td></tr>@endforeach</table></section><aside class="session-detail"><div class="detail-head"><h2>Session Details</h2><span>×</span></div><div class="detail-profile-session"><span>RK</span><div><strong>Ramesh Kumar</strong><small>USR001<br>9876543210<br>Karol Bagh, New Delhi</small></div></div><table class="session-info"><tr><td>Assignment</td><td>Canopy Installation</td></tr><tr><td>Project</td><td>City Clean Drive</td></tr><tr><td>Company</td><td>ABC Company</td></tr><tr><td>Activity Mode</td><td>Start - End</td></tr><tr><td>Current Duration</td><td>3h 25m (Active)</td></tr></table><section class="detail-box"><h3>Start Evidence</h3><div class="evidence"></div></section><section class="detail-box"><h3>Activity Timeline</h3><div class="timeline"><p>Session Started<br><small>28 Sep 2026, 09:15 AM</small></p><p>Start Location Captured<br><small>GPS location recorded</small></p><p>Activity In Progress<br><small>Duration: 3h 25m</small></p><p>Waiting for Completion</p></div></section></aside></div>
@endsection
