@extends('layout.app')
@section('title', 'Live Worker Tracking')
@push('styles')<link rel="stylesheet" href="{{ asset('css/activity-sessions.css') }}">@endpush
@section('content')
<nav class="breadcrumbs"><a href="{{ route('web.activity-sessions.index') }}">Activity Sessions</a><span>&rsaquo;</span><span>Live Tracking</span></nav>
<div class="page-heading tracking-heading"><div><h1>Live Worker Tracking</h1><p>Monitor real-time location, activity sessions and field movement of your team.</p></div><div class="tracking-tools"><a class="map-button" href="{{ route('web.activity-sessions.map') }}">View on Full Map</a></div></div>
<div class="tracking-stats"><article class="tracking-stat blue"><span>👥</span><div><h2>Total Workers</h2><strong>8</strong><p>+ 2 active now</p></div></article><article class="tracking-stat green"><span>⌖</span><div><h2>Active Now</h2><strong>5</strong><p>+ 62%</p></div></article><article class="tracking-stat orange"><span>◷</span><div><h2>On Break</h2><strong>1</strong><p>0%</p></div></article><article class="tracking-stat purple"><span>Ⅱ</span><div><h2>Offline</h2><strong>2</strong><p>+ 1</p></div></article></div>
<div class="tracking-layout"><aside class="tracking-list"><h2>Workers (8)</h2><div class="worker-filter"><input placeholder="Search worker..."><select><option>All Status</option></select></div>@foreach(['Ramesh Kumar','Priya Sharma','Amit Singh','Neha Verma','Suresh Patel','Vikram Yadav'] as $worker)<button class="worker-row {{ $loop->first ? 'active' : '' }}" type="button"><span>{{ substr($worker,0,1) }}</span><div><strong>{{ $worker }}</strong><small>USR00{{ $loop->iteration }} · Active now</small></div><i></i></button>@endforeach</aside><section class="map-panel"><div class="map-tabs"><button>Map</button><button>Satellite</button></div><div class="map-road"></div><div class="map-marker marker-one"><b>RK</b></div><div class="map-marker marker-two"><b>NV</b></div><div class="map-marker marker-three"><b>PS</b></div><div class="map-city">New Delhi</div><div class="map-legend"><span>Active (5)</span><span>On Break (1)</span><span>Offline (2)</span></div></section><aside class="worker-detail"><h2>Worker Details</h2><div class="detail-profile"><span>R</span><div><strong>Ramesh Kumar</strong><small>USR001<br>9876543210<br>Karol Bagh, New Delhi</small></div></div><section class="detail-section-session"><h3>Current Activity</h3><div class="detail-activity"><img src="{{ asset('images/admin-construction.jpg') }}"><div><strong>Poster Installation</strong><p>Started: 09:15 AM<br>Duration: 3h 25m</p></div></div></section></aside></div>
@endsection
