<div>
    <!-- Nothing worth having comes easy. - Theodore Roosevelt -->
</div>
@extends('layout.app')
@section('title', 'Reports')
@push('styles')<link rel="stylesheet" href="{{ asset('css/reports.css') }}">@endpush
@section('content')
<nav class="breadcrumbs"><a href="{{ route('web.dashboard') }}"><svg class="icon"><use href="#home"/></svg>Dashboard</a><span>&rsaquo;</span><span>Reports</span></nav>
<div class="page-heading reports-heading"><div><h1>Reports</h1><p>Analyze field activities, worker performance and project progress.</p></div><div class="report-tools"><select><option>01 Sep 2026 - 30 Sep 2026</option></select><select><option>All Companies</option></select><select><option>All Projects</option></select><button type="button" id="download-report">&#8681; Download Report</button></div></div>
<div class="report-stats"><article class="report-stat blue"><span><svg class="icon"><use href="#list"/></svg></span><div><h2>Total Assignments</h2><strong>156</strong><p>↑ 18%</p></div></article><article class="report-stat green"><span><svg class="icon"><use href="#check"/></svg></span><div><h2>Completed</h2><strong>112</strong><p>↑ 25%</p></div></article><article class="report-stat orange"><span><svg class="icon"><use href="#clock"/></svg></span><div><h2>In Progress</h2><strong>28</strong><p>↑ 12%</p></div></article><article class="report-stat purple"><span>!</span><div><h2>Pending</h2><strong>10</strong><p>↓ 5%</p></div></article><article class="report-stat blue"><span>×</span><div><h2>Rejected</h2><strong>6</strong><p>↑ 2%</p></div></article></div>
<div class="report-grid-top"><section class="report-panel"><h2>Activity Completion Trend</h2><div class="trend-chart"><i class="trend-line"></i><i class="trend-line blue"></i><i class="trend-line orange"></i><i class="trend-line red"></i></div><div class="chart-key"><span>Completed</span><span>In Progress</span><span>Pending</span><span>Rejected</span></div></section><section class="report-panel"><h2>Activity Type Distribution</h2><div class="donut-report"><div>156<small>Total</small></div></div><div class="type-list"><span><b><i></i>Installation</b>28 (18%)</span><span><b><i></i>Survey</b>22 (14%)</span><span><b><i></i>Cleaning</b>26 (17%)</span><span><b><i></i>Campaign</b>18 (12%)</span></div></section><section class="report-panel"><h2>Top Workers by Activity</h2><table class="worker-rank"><tr><th>#</th><th>Worker</th><th>Completed</th></tr><tr><td>1</td><td>Ramesh Kumar<br><small>USR001</small></td><td>28</td></tr><tr><td>2</td><td>Priya Sharma</td><td>22</td></tr><tr><td>3</td><td>Amit Singh</td><td>18</td></tr><tr><td>4</td><td>Neha Verma</td><td>15</td></tr><tr><td>5</td><td>Suresh Patel</td><td>14</td></tr></table></section></div>
<div class="report-grid-middle"><section class="report-panel"><h2>Project Wise Performance</h2>@foreach([['City Clean Drive','86%','46'],['Market Survey','72%','34'],['River Awareness','55%','27'],['Green City Initiative','61%','29'],['Poster Campaign','38%','15']] as $item)<div class="performance-row"><span>{{ $item[0] }}</span><div class="performance-bar"><span style="width:{{ $item[1] }}"></span></div><b>{{ $item[2] }}</b></div>@endforeach</section><section class="report-panel"><h2>Location Wise Activity Count</h2><div class="location-bars">@foreach([['34','85%','New Delhi'],['26','65%','Noida'],['22','55%','Gurgaon'],['18','45%','Faridabad'],['16','40%','Ghaziabad'],['12','30%','Indore']] as $location)<div>{{ $location[0] }}<i style="--height:{{ $location[1] }}"></i><small>{{ $location[2] }}</small></div>@endforeach</div></section></div>
<div class="report-grid-bottom"><section class="report-panel"><h2>Recent Activity Submissions</h2><table class="submission-table"><tr><th>#</th><th>Activity</th><th>Worker</th><th>Location</th><th>Submitted At</th><th>Status</th></tr><tr><td>1</td><td>Poster Installation</td><td>Ramesh Kumar</td><td>Karol Bagh</td><td>28 Sep 2026, 10:15 AM</td><td><span class="status-approved">Approved</span></td></tr><tr><td>2</td><td>Market Survey</td><td>Priya Sharma</td><td>Connaught Place</td><td>28 Sep 2026, 09:40 AM</td><td><span class="status-pending">Pending Review</span></td></tr><tr><td>3</td><td>Road Cleaning</td><td>Amit Singh</td><td>Lajpat Nagar</td><td>28 Sep 2026, 08:20 AM</td><td><span class="status-approved">Approved</span></td></tr></table></section><section class="report-panel"><h2>Activity Heat Map</h2><div class="heat-map"></div></section></div><div id="report-toast" class="company-toast" hidden></div>
@endsection
@push('scripts')<script src="{{ asset('js/reports.js') }}"></script>@endpush
