<div>
    <!-- I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison -->
</div>
@extends('layout.app')
@section('title', 'Activity Updates')
@push('styles')<link rel="stylesheet" href="{{ asset('css/activity-updates.css') }}">@endpush
@section('content')
@php($updates=[['Ramesh Kumar','Clean India Campaign','Poster Installation','3 posters pasted at market area.','Karol Bagh, New Delhi','10:32 AM','Active','active'],['Priya Sharma','City Promotion','Canopy Installation','Canopy frame installed. Next step pending.','Pitampura, New Delhi','09:15 AM','Active','active'],['Amit Singh','Health Awareness','Poster Installation','Poster pasted near school.','Mayur Vihar, New Delhi','11:20 AM','Pending','pending'],['Neha Verma','Clean India Campaign','Road Cleaning','Road cleaning done. Support from local people.','Lajpat Nagar, New Delhi','08:45 AM','Active','active'],['Suresh Patel','City Promotion','Poster Installation','5 posters pasted. Need more material.','Rohini, New Delhi','12:05 PM','Rejected','rejected'],['Vikram Yadav','Event Setup','Canopy Installation','Canopy fully installed and checked.','Connaught Place, New Delhi','01:18 PM','Active','active']])
<nav class="breadcrumbs"><a href="{{ route('web.dashboard') }}"><svg class="icon"><use href="#home"/></svg>Dashboard</a><span>&rsaquo;</span><span>Activity Updates</span></nav>
<div class="page-heading updates-heading"><div><h1>Activity Updates</h1><p>View real-time updates from field workers including photos, location and remarks.</p></div><button class="updates-export" type="button" id="export-updates">⇩ Export</button></div>
<div class="updates-stats"><article class="updates-stat blue"><span>♧</span><div><h2>Total Updates</h2><strong>246</strong><p>↑ 12%<br>vs last week</p></div></article><article class="updates-stat green"><span>♙</span><div><h2>Active Workers</h2><strong>14</strong><p>↑ 8%<br>vs last week</p></div></article><article class="updates-stat purple"><span>▧</span><div><h2>With Photos</h2><strong>220</strong><p>↑ 15%<br>vs last week</p></div></article><article class="updates-stat orange"><span>☷</span><div><h2>With Remarks</h2><strong>135</strong><p>↑ 10%<br>vs last week</p></div></article></div>
<div class="updates-filters"><input id="update-search" placeholder="Search by worker name, project, remark..."><select><option>Select Project</option></select><select><option>Select Worker</option></select><select><option>Select Activity Type</option></select><input type="date"><button type="button">Reset</button></div>
<section class="updates-table-card"><table class="updates-table"><tr><th>□</th><th>#</th><th>Photo</th><th>Worker</th><th>Project</th><th>Activity Type</th><th>Remark / Update</th><th>Location</th><th>Time</th><th>Status</th><th>Actions</th></tr>@foreach($updates as $update)<tr><td>□</td><td>{{ $loop->iteration }}</td><td><div class="update-photo"></div></td><td><div class="update-worker"><span class="update-avatar">{{ substr($update[0],0,1) }}</span><div><strong>{{ $update[0] }}</strong><small>USR00{{ $loop->iteration }}</small></div></div></td><td>{{ $update[1] }}</td><td><span class="update-type {{ $loop->even ? 'purple' : '' }}">{{ $update[2] }}</span></td><td>{{ $update[3] }}</td><td>⌖ {{ $update[4] }}</td><td>29 Sep 2026<br>{{ $update[5] }}</td><td><span class="update-status {{ $update[7] }}">{{ $update[6] }}</span></td><td><div class="update-actions"><button>◉</button><button>✎</button><button>×</button></div></td></tr>@endforeach</table><div class="updates-footer"><span>Show <button>10⌄</button> entries</span><div><button>‹</button><button class="active">1</button><button>2</button><button>3</button><button>›</button></div></div></section><div id="update-toast" class="company-toast" hidden></div>
@endsection
@push('scripts')<script src="{{ asset('js/activity-updates.js') }}"></script>@endpush
