@extends('layout.app')

@section('title', 'Activity Types')

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/activity-types.css') }}">
    <link rel="stylesheet" href="{{ asset('css/activity-types-fix.css') }}">
@endpush

@section('content')
    <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="{{ route('web.dashboard') }}"><svg class="icon"><use href="#home"/></svg>Dashboard</a><span>&rsaquo;</span><span>Activity Types</span></nav>
    <div class="page-heading activity-heading"><div><h1>Activity Types</h1><p>Create and manage different types of field activities for assignments.</p></div><a class="primary-button" href="{{ route('web.activity-types.create') }}"><span>+</span>Add New Activity Type</a></div>
    <div class="activity-stats"><article class="activity-stat blue"><span>☷</span><div><h2>Total Activity Types</h2><strong>8</strong></div></article><article class="activity-stat green"><span>✓</span><div><h2>Active Types</h2><strong>7</strong></div></article><article class="activity-stat red"><span>×</span><div><h2>Inactive Types</h2><strong>1</strong></div></article><article class="activity-stat purple"><span>♧</span><div><h2>Most Used Type</h2><strong class="type-name">Installation</strong><p>(42 assignments)</p></div></article></div>
    <div class="activity-layout">
        <section class="activity-table-card"><div class="activity-filters"><label class="company-search"><svg class="icon"><use href="#search"/></svg><input id="activity-search" type="search" placeholder="Search activity types..."></label><select id="activity-status"><option value="all">All Status</option><option value="Active">Active</option><option value="Inactive">Inactive</option></select></div><div class="company-table-scroll"><table class="activity-table"><thead><tr><th>#</th><th>Activity Type</th><th>Description</th><th>Default Mode</th><th>Status</th><th>Total Assignments</th><th>Actions</th></tr></thead><tbody id="activity-rows"></tbody></table><p id="activities-empty" class="empty-state" hidden>No activity types found.</p></div><div class="company-footer"><label class="page-size">Show <select id="activity-page-size"><option selected>10</option></select> entries</label><nav id="activity-pagination" class="pagination"></nav></div></section>
        <aside id="activity-form-panel" class="activity-form-card"><div class="form-heading"><h2>Add New Activity Type</h2><button id="close-activity-form" type="button">×</button></div><form id="activity-form"><label>Activity Name <em>*</em><input id="activity-name" required maxlength="80" placeholder="Enter activity type name"></label><label>Description <em>*</em><textarea id="activity-description" required maxlength="500" placeholder="Enter detailed description of this activity type..."></textarea><small id="activity-description-count">0/500</small></label><fieldset><legend>Default Activity Mode <em>*</em></legend><label><input type="radio" name="mode" value="Single Submission" checked> Single Submission <small>Worker submits one time with photo and location</small></label><label><input type="radio" name="mode" value="Start - End"> Start - End <small>Worker starts activity and ends it with time tracking</small></label><label><input type="radio" name="mode" value="Continuous Tracking"> Continuous Tracking <small>Real-time location tracking during activity</small></label></fieldset><fieldset><legend>Icon <em>*</em></legend><div class="icon-options"><button type="button" class="icon-choice selected" data-icon="🔧">🔧</button><button type="button" class="icon-choice" data-icon="📄">📄</button><button type="button" class="icon-choice" data-icon="🧹">🧹</button><button type="button" class="icon-choice" data-icon="📍">📍</button><button type="button" class="icon-choice" data-icon="📣">📣</button><button type="button" class="icon-choice" data-icon="🏪">🏪</button></div></fieldset><label class="switch-label">Status <em>*</em><span><input id="activity-active" type="checkbox" checked><i></i> Active</span></label><div class="activity-form-actions"><button id="cancel-activity" class="secondary-button" type="button">Cancel</button><button class="primary-button" type="submit">Create Activity Type</button></div></form></aside>
    </div><div id="activity-toast" class="company-toast" hidden></div>
@endsection
@push('scripts')<script src="{{ asset('js/activity-types.js') }}"></script>@endpush
